### ISSUE TITLE
RFC - Avoid Cannot access property on find()->first()->my_field

### ISSUE THREAD

**Issue by gersonfs** [CakeDC/cakephp-phpstan#1]
Hello!

Some tip for avoid `Cannot access property $my_field on array|Cake\Datasource\EntityInterface` error on PHPStan when do this: 

```
$obj = $this->find('all')->first();
echo $obj->my_field;
```
Currently i use annotations on every ...->first() call like:
```
/** @var \App\Model\Entity\MyEntity $obj */
$obj = $this->find('all')->first();
```

But i think there is a better sollution than fill my code with comments.

**Comment by dereuromark** [comment]
I am not sure if there is an option here
We might always have to annotate as finding dynamically of hydrate false is set, might be super hard.
