### ISSUE TITLE
CakePHP 5 stan rule for `Cake\ORM\Table::get()` with `contain` named argument

### ISSUE THREAD

**Issue by LordSimal** [CakeDC/cakephp-phpstan#13]
After upgrading to Cake5 I get a bunch of PHPStan errors like
```
Unknown parameter $contain in call to method App\Model\Table\CategoriesTable::get().  
```

For e.g. `$this->Categories->get($id, contain: ['OtherData'])` because the named argument `contain` is not in the definition of that base method.

It of course is still valid so it would be cool if this extension can tell PHPStan that this is fine.

**Comment by rochamarcelo** [comment]
This is odd, I don't get errors on PHPStan playground https://phpstan.org/r/6cd20648-4f63-48c9-9f89-546a488b0e7a

**Comment by LordSimal** [comment]
I see whats the problem... this needs to be fixed in the ide helper.

Currently I have this in my table class:
```
 * @method \App\Model\Entity\Category get($primaryKey, $options = [])
```
because thats still the old Cake4 version of `->get()`

If I remove that line stan is happy with what core provides.
