### ISSUE TITLE
Cake5 release

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/cakephp-phpstan#16]
Any chance there could be a cake5 release asap?
We could need it for the cakefest I am sure.

**Comment by dereuromark** [comment]
ping @skie @steinkel

**Comment by steinkel** [comment]
hey @dereuromark please check https://github.com/CakeDC/cakephp-phpstan/releases/tag/3.0.0

**Comment by dereuromark** [comment]
Thx :)
