### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/cakephp-phpstan#3]
can you do a new release for the 4.3 adjustments?

**Comment by LordSimal** [comment]
Maybe include the new PHPStan 1.0 dependency as well? 😄 
#4

**Comment by dereuromark** [comment]
maybe a patch first for old, then do a new minor for 1.0.0 of there are breaking changes?

**Comment by dereuromark** [comment]
@steinkel Can you do that maybe?

**Comment by dereuromark** [comment]
or @rochamarcelo

**Comment by steinkel** [comment]
sure thing
