### ISSUE TITLE
Call to `App\Model\Table\CategoriesTable::belongsTo` with unknown option "joinTable".

### ISSUE THREAD

**Issue by LordSimal** [CakeDC/cakephp-phpstan#32]
After updating from 3.0.1 to 3.1.2 this error pops up for some of my table classes:
```
  55     Call to App\Model\Table\CategoriesTable::belongsTo with unknown option "joinTable".         
  55     Call to App\Model\Table\CategoriesTable::belongsTo with unknown option "targetForeignKey".  
```

**Comment by rochamarcelo** [comment]
@LordSimal these keys are not used for belongsTo association https://book.cakephp.org/5/en/orm/associations.html#belongsto-associations

**Comment by LordSimal** [comment]
Well... why didn't I notice this in the first hand. Very cool that this plugin cleans up association configs 👍🏻
