### ISSUE TITLE
PHPStan v2 compatibility

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/cakephp-phpstan#40]
https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants

probably as major v4 of this repo

**Comment by rochamarcelo** [comment]
4.0 should be realized ASAP we have worked on the upgrade https://github.com/CakeDC/cakephp-phpstan/tree/4.next-cake5

**Comment by rochamarcelo** [comment]
4.0.0 released
