### ISSUE TITLE
Command ConsoleIo::helper() issue

### ISSUE THREAD

**Issue by dereuromark** [CakeDC/cakephp-phpstan#9]
```
  Line   FooBarCommand.php                                        
 ------ --------------------------------------------------------- 
  40     Call to an undefined method Cake\Console\Helper::foo().  
 ------ --------------------------------------------------------- 
```
According to https://github.com/CakeDC/cakephp-phpstan/blob/master/extension.neon#L69-L71 it should work however to autocomplete

```php
    public function execute(Arguments $args, ConsoleIo $io)
    {
        $helper = $io->helper('BazBaz');
        $x = $helper->foo();
```

And helper
```php
namespace App\Shell\Helper;

use Cake\Console\Helper;

class BazBazHelper extends Helper
{
    public function output(array $args): void
    {
    }

    public function foo(): string
    {
        return '';
    }
}
```

I added IDE part in https://github.com/dereuromark/cakephp-ide-helper/pull/265 and wanted to check if PHPStan issue is also solved, but seems not.

**Comment by rochamarcelo** [comment]
I see that you are using a command,  that line is for shell class (https://github.com/CakeDC/cakephp-phpstan/blob/master/extension.neon#L69-L71) but we should support ConsoleIo class too.

**Comment by dereuromark** [comment]
Yeah, it should, thats why I was surprised it doesnt work

**Comment by rochamarcelo** [comment]
Closing issue pull request was sent https://github.com/CakeDC/cakephp-phpstan/pull/10 .  Thank you.
